// GET //

export const GET_ALL_COURSES = "GET_ALL_COURSES"
export const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES"
export const GET_DETAIL_COURSES = "GET_DETAIL_COURSES"
export const GET_COURSE_BY_NAME = "GET_COURSE_BY_NAME"
export const GET_COURSES_SCORE = "GET_COURSES_SCORE"
export const GET_USER = "GET_USER"
export const GET_ORDER = "GET_ORDER"

// ORDES //

export const ORDER_BY_NAME = "ORDER_BY_NAME"
export const ORDER_BY_SCORE = "ORDER_BY_SCORE"
export const ORDER_BY_PRICE = "ORDER_BY_PRICE"

// FILTERS //

export const FILTER_BY_CATEGORIES = "FILTER_BY_CATEGORIES"
export const FILTER_BY_DURATION = "FILTER_BY_DURATION"
export const FILTER_BY_RANGE_PRICE = "FILTER_BY_RANGE_PRICE"
export const FILTER_BY_STARS = "FILTER_BY_STARS"